
from django.contrib import admin
from django.urls import path, include

from MyApp import views

urlpatterns = [
    path('login/',views.login),
    path('login_post/',views.login_post),
    path('forgot/',views.forgot),
    path('forget_post/',views.forget_post),
    path('logout/',views.logout),
    path('add_department/',views.add_department),
    path('add_department_post/',views.add_department_post),
    path('admin_home/',views.admin_home),
    path('add_hod/',views.add_hod),
    path('get_staff/',views.get_staff),
    path('add_hod_post/',views.add_hod_post),
    path('add_staff/',views.add_staff),
    path('add_staff_post/',views.add_staff_post),
    path('admin_change_password/',views.admin_change_password),
    path('admin_change_password_post/',views.admin_change_password_post),
    path('edit_department/<id>',views.edit_department),
    path('edit_department_post/',views.edit_department_post),
    path('delete_dept/<id>',views.delete_dept),
    path('edit_hod/<id>',views.edit_hod),
    path('delete_hod/<id>',views.delete_hod),
    path('edit_hod_post/',views.edit_hod_post),
    path('edit_staff/<id>',views.edit_staff),
    path('delete_staff/<id>',views.delete_staff),
    path('edit_staff_post/',views.edit_staff_post),
    path('view_approved_requests/',views.view_approved_requests),
    path('view_approved_requests_post/',views.view_approved_requests_post),
    path('view_department/',views.view_department),
    path('view_department_post/',views.view_department_post),
    path('view_hod/',views.view_hod),
    path('view_hod_post/',views.view_hod_post),
    path('view_leave_request/',views.view_leave_request),
    path('view_leave_request_post/',views.view_leave_request_post),
    path('view_rejected_request/',views.view_rejected_request),
    path('view_rejected_request_post/',views.view_rejected_request_post),
    path('view_service_details_of_other_staff/<id>',views.view_service_details_of_other_staff),
    path('view_service_details_of_other_staff_post/',views.view_service_details_of_other_staff_post),
    path('view_staff/',views.view_staff),
    path('view_staff_post/',views.view_staff_post),
    path('new_requests/',views.new_requests),
    path('new_requests_post/',views.new_requests_post),
    path('approve_staff/<id>',views.approve_staff),
    path('reject_staff/<id>',views.reject_staff),
    path('rejected_req/',views.rejected_req),
    path('rejected_req_post/',views.rejected_req_post),
    path('edit_profile/',views.edit_profile),
    path('edit_profile_post/',views.edit_profile_post),
    path('view_services/<id>',views.view_services),
    path('view_services_post/',views.view_services_post),
    path('view_attendance/',views.view_attendance),
    path('view_attendance_post/',views.view_attendance_post),
    path('attendance_date/',views.attendance_date),
    path('attendance_date_post/',views.attendance_date_post),

    #Hod

    path('hod_change_password/',views.hod_change_password),
    path('hod_change_password_post/',views.hod_change_password_post),
    path('send_leave_request/',views.send_leave_request),
    path('send_leave_request_post/',views.send_leave_request_post),
    path('hod_home/',views.hod_home),
    path('view_forwarded_leave_request/',views.view_forwarded_leave_request),
    path('view_forwarded_leave_request_post/',views.view_forwarded_leave_request_post),
    path('view_leave_request_and_forward_to_principal/',views.view_leave_request_and_forward_to_principal),
    path('view_leave_request_and_forward_to_principal_post/',views.view_leave_request_and_forward_to_principal_post),
    path('hod_view_leave_request/',views.hod_view_leave_request),
    path('hod_view_leave_request_post/',views.hod_view_leave_request_post),
    path('view_profile/',views.view_profile),
    # path('view_profile_post',views.view_profile_post),
    path('hod_view_service_details_of_other_staff/<id>',views.hod_view_service_details_of_other_staff),
    path('hod_view_service_details_of_other_staff_post/',views.hod_view_service_details_of_other_staff_post),
    path('view_service_details/',views.view_service_details),
    path('view_service_details_post/',views.view_service_details_post),
    path('hod_view_staff/',views.hod_view_staff),
    path('hod_view_staff/',views.hod_view_staff),
    path('hod_view_staff_post/',views.hod_view_staff_post),
    path('hod_edit_staff/<id>',views.hod_edit_staff),
    path('hod_edit_staff_post/',views.hod_edit_staff_post),
    path('hod_delete_staff/<id>', views.hod_delete_staff),
    path('approve_request_post/<id>',views.approve_request_post),
    path('admin_approve_request_post/<id>',views.admin_approve_request_post),
    path('reject_request_post/<id>',views.reject_request_post),
    path('admin_reject_request_post/<id>',views.admin_reject_request_post),
    path('hod_view_services/<id>',views.hod_view_services),
    path('hod_view_services_post/',views.hod_view_services_post),
    path('hod_view_my_leave_request_status/',views.hod_view_my_leave_request_status),
    path('hod_view_my_leave_request_status_post/',views.hod_view_my_leave_request_status_post),
    path('new_register/',views.new_register),
    path('View_stud_dep/',views.View_stud_dep),
    path('staff_edit_profile/',views.staff_edit_profile),
    path('hod_add_services/',views.hod_add_services),
    path('hod_add_services_post/',views.hod_add_services_post),
    path('hod_view_my_services/',views.hod_view_my_services),
    path('hod_view_my_services_post/',views.hod_view_my_services_post),




    path('staff_login/',views.staff_login),
    path('staff_view_profile/',views.staff_view_profile),
    path('view_dept_staff/',views.view_dept_staff),
    path('staff_send_leave_req/',views.staff_send_leave_req),
    path('staff_view_leave_req_status/',views.staff_view_leave_req_status),
    path('staff_attendance_history/',views.staff_attendance_history),
    path('staff_change_pswd/',views.staff_change_pswd),
    path('add_services/',views.add_services),
    path('staff_view_services/',views.staff_view_services),
    path('forget_password_post/',views.forget_password_post),
    path('staff_loginnew/',views.staff_loginnew),
    path('and_Checkin/',views.and_Checkin),

]
