# Generated by Django 3.2.22 on 2024-04-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('Photo', models.CharField(max_length=100)),
                ('Status', models.CharField(default='pending', max_length=100)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.department')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=100)),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField()),
                ('Duration', models.CharField(max_length=100)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('LeaveType', models.CharField(max_length=100)),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.hod')),
                ('LOGIN', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
        migrations.AddField(
            model_name='hod',
            name='STAFF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff'),
        ),
        migrations.CreateModel(
            name='Finger_print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=250)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Attendance', models.CharField(max_length=100)),
                ('Time', models.CharField(default='', max_length=100)),
                ('STAFF', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
        ),
    ]
