# Generated by Django 3.2.22 on 2024-04-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='HOD',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.hod'),
        ),
    ]
