# Generated by Django 3.2.22 on 2024-04-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_leave_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='HOD',
        ),
    ]
